FROM python:3-alpine
apt-get install pip3
pip3 install flask
pip3 install mysql-connector-python
copy *.p*
python3 api.py
# Add your instructions to dockerize the application
# App must run on port 8000
